---
version: '3'

services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
  wordpress:
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
    - db
    restart: always
    image: wordpress:latest
    ports:
    - 8090:80
    volumes:
    - wordpress:/var/www/html
    - ./wp-content:/var/www/html/wp-content
  wp-cli:
    image: wordpress:cli
    user: '33:33'
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - ./bin/install-wp.sh:/usr/local/bin/install-wp
    links:
      - db
    command: "--info"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    restart: always
    ports:
     - 8091:80
    volumes:
     - /sessions
  composer:
    image: composer
    command: install
    working_dir: /var/www/html
    depends_on:
    - wordpress
    volumes:
    - ./composer.json:/var/www/html/composer.json
    - ./composer.lock:/var/www/html/composer.lock
    - ./wp-content:/var/www/html/wp-content
    - wordpress:/var/www/html
    links:
    - wordpress:wordpress
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
    - "1025:1025"
    - "8025:8025"
volumes:
  db_data:
  wordpress:
