---
version: '3'

services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
  wordpress:
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
    - db
    image: wordpress:latest
    ports:
    - 8000:80
    restart: always
    volumes:
    - wordpress:/var/www/html
    - ./wp-content/themes/kicks-app:/var/www/html/wp-content/themes/kicks-app
    - /var/www/html/wp-content/themes/kicks-app/node_modules
    - /var/www/html/wp-content/themes/kicks-app/js
    - /var/www/html/wp-content/themes/kicks-app/css
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8001:80
    volumes:
     - /sessions
  composer:
    image: composer/composer:php7
    container_name: composer
    command: install
    working_dir: /var/www/html
    depends_on:
    - wordpress
    volumes:
    - ./composer.json:/var/www/html/composer.json
    - wordpress:/var/www/html
volumes:
  db_data:
  wordpress:
