# Development
development:
  name: dr-thede-test
  user: root
  password: root
  host: localhost
  charset: utf8
# Staging
test:
  name: kicks-app-staging
  user: root
  password: root
  host: localhost
  charset: utf8
# Production
production:
  name: kicks-app-production
  user: root
  password: root
  host: localhost
  charset: utf8